rating_subdivision:
    resource: "@RatingSubdivisionBundle/Controller/"
    type:     annotation
    prefix:   /

rating_admin:
    resource: "@RatingAdminBundle/Controller/"
    type:     annotation
    prefix:   /

stl_test:
    resource: "@STLTestBundle/Controller/"
    type:     annotation
    prefix:   /

rating_user:
    resource: "@RatingUserBundle/Controller/"
    type:     annotation
    prefix:   /

rating_profile:
    resource: "@RatingProfileBundle/Controller/"
    type:     annotation
    prefix:   /

rating_main:
    resource: "@RatingMainBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@RatingUserBundle/Resources/config/routing/all.xml"


