system_app:
    resource: "@ServiceBundle/Controller/"
    type:     annotation
    prefix:   /

rating_subdivision:
    resource: "@SubdivisionBundle/Controller/"
    type:     annotation
    prefix:   /

rating_admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

rating_teachers:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

rating_profile:
    resource: "@ProfileBundle/Controller/"
    type:     annotation
    prefix:   /

rating_main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

rating_app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /