security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        main:
            entity:
                class: RatingUserBundle:User
                property: email


    firewalls:
        main:
            pattern: ^/
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard/, role: ROLE_USER }
        - { path: ^/profile/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }