services:

  google.client:
    class: Rating\UserBundle\Security\GoogleService
    arguments: ['@router', '@service_container']

  google.oauth:
      class: Rating\UserBundle\Security\GoogleOAuth
      arguments: ['@google.client', '@service_container', '@request_stack']
  user.manager:
      class: Rating\UserBundle\Security\UserManager
      arguments: ['@service_container']
