services:
    measure:
        class: AppBundle\Manager\MeasureManager
        public: true
        arguments:
            - @doctrine.orm.default_entity_manager
            - @service_container
    year.manager:
        class: AppBundle\Manager\YearManager
        public: true
        arguments:
            - @doctrine.orm.default_entity_manager
            - @service_container

    security_handler:
        class: Rating\UserBundle\Auth\SecurityHandler
        arguments:  [@router]